/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Buscador;

import Objetos.Cartas;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM1_16
 */
public class Principal extends javax.swing.JFrame {

    private Cartas c;
    private Conexion con = new Conexion();
    private Metodos met = new Metodos();
    private String nombre = null, color = null, rareza = null, habilidad = null, tipo = null,nombreViejo = null;
    private int cmc = 0, fuerza = -1, defensa = -1;
    private Object[][] dtCartas;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        con.GetConnection();
        this.cENombre.setModel( con.LlenarComboBox());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vBuscar = new javax.swing.JFrame();
        vAñadir = new javax.swing.JDialog();
        vEditar = new javax.swing.JDialog();
        vAcerca = new javax.swing.JDialog();
        pInicial = new javax.swing.JPanel();
        paneles = new javax.swing.JTabbedPane();
        pPrincipal = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pVisualizar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bVisualizar = new javax.swing.JButton();
        pAñadir = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tANombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rAAzul = new javax.swing.JRadioButton();
        rABlanco = new javax.swing.JRadioButton();
        rANegro = new javax.swing.JRadioButton();
        rARojo = new javax.swing.JRadioButton();
        rAVerde = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        cATipo = new javax.swing.JComboBox();
        cARareza = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        tACmc = new javax.swing.JTextField();
        eAFuerza = new javax.swing.JLabel();
        eADefensa = new javax.swing.JLabel();
        cAFuerza = new javax.swing.JComboBox();
        cADefensa = new javax.swing.JComboBox();
        bAñadir = new javax.swing.JButton();
        rAIncoloro = new javax.swing.JRadioButton();
        tAhabilidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tAimagen = new javax.swing.JTextField();
        pEditar = new javax.swing.JPanel();
        bEditar = new javax.swing.JButton();
        cEDefensa = new javax.swing.JComboBox();
        eEDefensa = new javax.swing.JLabel();
        eEFuerza = new javax.swing.JLabel();
        cEFuerza = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        tECmc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cETipo = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cERareza = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        tENombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cENombre = new javax.swing.JComboBox();
        rEAzul = new javax.swing.JRadioButton();
        rERojo = new javax.swing.JRadioButton();
        rEBlanco = new javax.swing.JRadioButton();
        rEVerde = new javax.swing.JRadioButton();
        rENegro = new javax.swing.JRadioButton();
        rEIncoloro = new javax.swing.JRadioButton();
        tEhabilidad = new javax.swing.JTextField();
        tEimagen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pBuscar = new javax.swing.JPanel();
        bBuscar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        tBNombre = new javax.swing.JTextField();
        cBTipo = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        cBRareza = new javax.swing.JComboBox();
        tBhabilidad = new javax.swing.JTextField();
        menu = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mVisualizar = new javax.swing.JMenuItem();
        mAñadir = new javax.swing.JMenuItem();
        mEditar = new javax.swing.JMenuItem();
        mBuscar = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        macerca = new javax.swing.JMenuItem();

        javax.swing.GroupLayout vBuscarLayout = new javax.swing.GroupLayout(vBuscar.getContentPane());
        vBuscar.getContentPane().setLayout(vBuscarLayout);
        vBuscarLayout.setHorizontalGroup(
            vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        vBuscarLayout.setVerticalGroup(
            vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vAñadirLayout = new javax.swing.GroupLayout(vAñadir.getContentPane());
        vAñadir.getContentPane().setLayout(vAñadirLayout);
        vAñadirLayout.setHorizontalGroup(
            vAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        vAñadirLayout.setVerticalGroup(
            vAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vEditarLayout = new javax.swing.GroupLayout(vEditar.getContentPane());
        vEditar.getContentPane().setLayout(vEditarLayout);
        vEditarLayout.setHorizontalGroup(
            vEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        vEditarLayout.setVerticalGroup(
            vEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout vAcercaLayout = new javax.swing.GroupLayout(vAcerca.getContentPane());
        vAcerca.getContentPane().setLayout(vAcercaLayout);
        vAcercaLayout.setHorizontalGroup(
            vAcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        vAcercaLayout.setVerticalGroup(
            vAcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BuscadorMTG");
        setMinimumSize(new java.awt.Dimension(680, 525));
        setPreferredSize(new java.awt.Dimension(680, 525));
        setResizable(false);

        pInicial.setMinimumSize(new java.awt.Dimension(680, 680));
        pInicial.setPreferredSize(new java.awt.Dimension(680, 680));

        paneles.setMinimumSize(new java.awt.Dimension(680, 680));
        paneles.setPreferredSize(new java.awt.Dimension(680, 680));

        pPrincipal.setMinimumSize(new java.awt.Dimension(670, 670));
        pPrincipal.setPreferredSize(new java.awt.Dimension(670, 670));

        jLabel34.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        jLabel34.setText("Bienvenido a nuestra base de datos de cartas de Magic the Gathering");

        jLabel35.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        jLabel35.setText("Esperamos que tengas una grata experiencia.");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/magic_the_gathering.png"))); // NOI18N

        javax.swing.GroupLayout pPrincipalLayout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(pPrincipalLayout);
        pPrincipalLayout.setHorizontalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel34))
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel35))
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel11)))
                .addGap(107, 107, 107))
        );
        pPrincipalLayout.setVerticalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addContainerGap(337, Short.MAX_VALUE))
        );

        paneles.addTab("Principal", pPrincipal);

        pVisualizar.setMinimumSize(new java.awt.Dimension(670, 670));
        pVisualizar.setPreferredSize(new java.awt.Dimension(670, 670));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Rareza", "Habilidad"
            }
        ));
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabla);

        jLabel1.setText("Bienvenido al visualizador de nuestro programa, presione el siguiente boton para visualizar ");

        jLabel2.setText("la lista completa de cartas almacenada en nuestro servidor.");

        bVisualizar.setText("Visualizar cartas");
        bVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pVisualizarLayout = new javax.swing.GroupLayout(pVisualizar);
        pVisualizar.setLayout(pVisualizarLayout);
        pVisualizarLayout.setHorizontalGroup(
            pVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVisualizarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(pVisualizarLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(bVisualizar)))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(pVisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 655, Short.MAX_VALUE)
                .addContainerGap())
        );
        pVisualizarLayout.setVerticalGroup(
            pVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVisualizarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );

        paneles.addTab("Visualizar lista", pVisualizar);

        pAñadir.setMinimumSize(new java.awt.Dimension(670, 670));
        pAñadir.setPreferredSize(new java.awt.Dimension(670, 670));

        jLabel3.setText("En esta pestaña puedes añadir una carta nueva a nuestra base de datos, para ello cubre el");

        jLabel4.setText("siguiente formulario y presiona añadir:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Tipo:");

        jLabel7.setText("Habilidad:");

        jLabel8.setText("Color:");

        rAAzul.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rAAzul.setForeground(new java.awt.Color(0, 51, 204));
        rAAzul.setText(" Azul +");
        rAAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAAzulActionPerformed(evt);
            }
        });

        rABlanco.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rABlanco.setForeground(new java.awt.Color(255, 255, 204));
        rABlanco.setText("Blanco @ ");
        rABlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rABlancoActionPerformed(evt);
            }
        });

        rANegro.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rANegro.setText(" Negro =");
        rANegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rANegroActionPerformed(evt);
            }
        });

        rARojo.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rARojo.setForeground(new java.awt.Color(255, 0, 0));
        rARojo.setText(" Rojo <");
        rARojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rARojoActionPerformed(evt);
            }
        });

        rAVerde.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rAVerde.setForeground(new java.awt.Color(51, 130, 60));
        rAVerde.setText(" Verde >");
        rAVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAVerdeActionPerformed(evt);
            }
        });

        jLabel9.setText("Rareza:");

        cATipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona un tipo", "Artefacto", "Criatura", "Conjuro", "Encantamiento", "Instantaneo", "Tierra" }));
        cATipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cATipoActionPerformed(evt);
            }
        });

        cARareza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una rareza", "Comun", "Infrecuente", "Rara", "Rara Mitica" }));
        cARareza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cARarezaActionPerformed(evt);
            }
        });

        jLabel10.setText("Coste de Mana Convertido:");

        eAFuerza.setText("Fuerza:");
        eAFuerza.setEnabled(false);

        eADefensa.setText("Defensa:");
        eADefensa.setEnabled(false);

        cAFuerza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una fuerza", "-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cAFuerza.setEnabled(false);
        cAFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAFuerzaActionPerformed(evt);
            }
        });

        cADefensa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una defensa", "-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cADefensa.setEnabled(false);
        cADefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cADefensaActionPerformed(evt);
            }
        });

        bAñadir.setText("Añadir");
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirActionPerformed(evt);
            }
        });

        rAIncoloro.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rAIncoloro.setForeground(new java.awt.Color(102, 102, 102));
        rAIncoloro.setText("Incoloro");
        rAIncoloro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAIncoloroActionPerformed(evt);
            }
        });

        jLabel12.setText("Link Imagen:");

        javax.swing.GroupLayout pAñadirLayout = new javax.swing.GroupLayout(pAñadir);
        pAñadir.setLayout(pAñadirLayout);
        pAñadirLayout.setHorizontalGroup(
            pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAñadirLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAñadirLayout.createSequentialGroup()
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bAñadir)
                            .addComponent(jLabel3))
                        .addGap(184, 207, Short.MAX_VALUE))
                    .addGroup(pAñadirLayout.createSequentialGroup()
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pAñadirLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(tAimagen))
                            .addGroup(pAñadirLayout.createSequentialGroup()
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAñadirLayout.createSequentialGroup()
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cATipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tANombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel8)
                                    .addGroup(pAñadirLayout.createSequentialGroup()
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rABlanco)
                                            .addComponent(rANegro)
                                            .addComponent(rAAzul))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rARojo)
                                            .addComponent(rAIncoloro)
                                            .addComponent(rAVerde)))
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAñadirLayout.createSequentialGroup()
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(eAFuerza)
                                            .addComponent(eADefensa))
                                        .addGap(23, 23, 23)
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cADefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cAFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAñadirLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tACmc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAñadirLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cARareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAñadirLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(tAhabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pAñadirLayout.setVerticalGroup(
            pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAñadirLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAñadirLayout.createSequentialGroup()
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tANombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cATipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rAAzul)
                            .addComponent(rARojo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rABlanco)
                            .addComponent(rAVerde))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rANegro)
                            .addComponent(rAIncoloro)))
                    .addGroup(pAñadirLayout.createSequentialGroup()
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tAhabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(21, 21, 21)
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cARareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(pAñadirLayout.createSequentialGroup()
                                .addComponent(tACmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eAFuerza)
                                    .addComponent(cAFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(21, 21, 21)
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eADefensa)
                            .addComponent(cADefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tAimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bAñadir)
                .addContainerGap(345, Short.MAX_VALUE))
        );

        paneles.addTab("Añadir carta", pAñadir);

        pEditar.setMinimumSize(new java.awt.Dimension(670, 670));
        pEditar.setPreferredSize(new java.awt.Dimension(670, 670));

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        cEDefensa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una defensa", "-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cEDefensa.setEnabled(false);
        cEDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEDefensaActionPerformed(evt);
            }
        });

        eEDefensa.setText("Defensa:");
        eEDefensa.setEnabled(false);

        eEFuerza.setText("Fuerza:");
        eEFuerza.setEnabled(false);

        cEFuerza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una fuerza", "-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cEFuerza.setEnabled(false);
        cEFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEFuerzaActionPerformed(evt);
            }
        });

        jLabel15.setText("Coste de Mana Convertido:");

        jLabel16.setText("Color:");

        jLabel17.setText("Tipo:");

        cETipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona un tipo", "Artefacto", "Criatura", "Conjuro", "Encantamiento", "Instantaneo", "Tierra" }));
        cETipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cETipoActionPerformed(evt);
            }
        });

        jLabel18.setText("Rareza:");

        cERareza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una rareza", "Comun", "Infrecuente", "Rara", "Rara Mitica" }));
        cERareza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cERarezaActionPerformed(evt);
            }
        });

        jLabel19.setText("Habilidad:");

        jLabel20.setText("Nombre:");

        jLabel21.setText("formulario y presiona editar:");

        jLabel22.setText("En esta pestaña puedes editar una carta ya existente, para ello cubre el siguiente");

        jLabel23.setText("Indica la carta a editar:");

        cENombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cENombreActionPerformed(evt);
            }
        });

        rEAzul.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rEAzul.setForeground(new java.awt.Color(0, 51, 204));
        rEAzul.setText(" Azul +");

        rERojo.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rERojo.setForeground(new java.awt.Color(255, 0, 0));
        rERojo.setText("Rojo < ");

        rEBlanco.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rEBlanco.setForeground(new java.awt.Color(255, 255, 204));
        rEBlanco.setText("Blanco @ ");

        rEVerde.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rEVerde.setForeground(new java.awt.Color(51, 130, 60));
        rEVerde.setText("Verde > ");

        rENegro.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rENegro.setText(" Negro =");

        rEIncoloro.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rEIncoloro.setForeground(new java.awt.Color(102, 102, 102));
        rEIncoloro.setText("Incoloro");

        jLabel13.setText("Link Imagen:");

        javax.swing.GroupLayout pEditarLayout = new javax.swing.GroupLayout(pEditar);
        pEditar.setLayout(pEditarLayout);
        pEditarLayout.setHorizontalGroup(
            pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEditarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pEditarLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(tEimagen))
                    .addGroup(pEditarLayout.createSequentialGroup()
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEditarLayout.createSequentialGroup()
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel17))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cETipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tENombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel16)
                            .addGroup(pEditarLayout.createSequentialGroup()
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rEBlanco)
                                    .addComponent(rENegro)
                                    .addComponent(rEAzul))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rERojo)
                                    .addComponent(rEIncoloro)
                                    .addComponent(rEVerde))))
                        .addGap(18, 18, 18)
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEditarLayout.createSequentialGroup()
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eEFuerza)
                                    .addComponent(eEDefensa))
                                .addGap(23, 23, 23)
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cEDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cEFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pEditarLayout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tECmc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pEditarLayout.createSequentialGroup()
                                    .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel19)
                                        .addComponent(jLabel18))
                                    .addGap(18, 18, 18)
                                    .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tEhabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cERareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(bEditar)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addGroup(pEditarLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cENombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        pEditarLayout.setVerticalGroup(
            pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(cENombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tENombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(tEhabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cETipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cERareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(tECmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEditarLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eEFuerza)
                            .addComponent(cEFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eEDefensa)
                            .addComponent(cEDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pEditarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rEAzul)
                            .addComponent(rERojo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rEBlanco)
                            .addComponent(rEVerde))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rENegro)
                            .addComponent(rEIncoloro))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tEimagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bEditar)
                .addContainerGap(319, Short.MAX_VALUE))
        );

        paneles.addTab("Editar carta", pEditar);

        pBuscar.setMinimumSize(new java.awt.Dimension(670, 670));
        pBuscar.setPreferredSize(new java.awt.Dimension(670, 670));

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        jLabel25.setText("Tipo:");

        jLabel26.setText("Nombre:");

        jLabel27.setText("siguiente formulario y presiona el boton para buscar:");

        jLabel28.setText("En esta pestaña puedes buscar una carta de nuestra base de datos, para ello cubre el");

        cBTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona un tipo", "Artefacto", "Criatura", "Conjuro", "Encantamiento", "Instantaneo", "Tierra" }));
        cBTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBTipoActionPerformed(evt);
            }
        });

        jLabel29.setText("Habilidad:");

        jLabel30.setText("Rareza:");

        cBRareza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una rareza", "Comun", "Infrecuente", "Rara", "Rara Mitica" }));
        cBRareza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBRarezaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBuscarLayout = new javax.swing.GroupLayout(pBuscar);
        pBuscar.setLayout(pBuscarLayout);
        pBuscarLayout.setHorizontalGroup(
            pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBuscarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBuscarLayout.createSequentialGroup()
                        .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tBhabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cBRareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 192, Short.MAX_VALUE))
                    .addGroup(pBuscarLayout.createSequentialGroup()
                        .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bBuscar)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(20, 20, 20))))
        );
        pBuscarLayout.setVerticalGroup(
            pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBuscarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(33, 33, 33)
                .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(tBhabilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(cBRareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(bBuscar)
                .addContainerGap(454, Short.MAX_VALUE))
        );

        paneles.addTab("Buscar carta", pBuscar);

        javax.swing.GroupLayout pInicialLayout = new javax.swing.GroupLayout(pInicial);
        pInicial.setLayout(pInicialLayout);
        pInicialLayout.setHorizontalGroup(
            pInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInicialLayout.createSequentialGroup()
                .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pInicialLayout.setVerticalGroup(
            pInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInicialLayout.createSequentialGroup()
                .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );

        mArchivo.setText("Archivo");

        mVisualizar.setText("Visualizar lista  de cartas");
        mArchivo.add(mVisualizar);

        mAñadir.setText("Añadir carta nueva");
        mArchivo.add(mAñadir);

        mEditar.setText("Editar una carta");
        mArchivo.add(mEditar);

        mBuscar.setText("Buscar una carta");
        mArchivo.add(mBuscar);

        mSalir.setText("Salir");
        mArchivo.add(mSalir);

        menu.add(mArchivo);

        mAyuda.setText("Ayuda");

        macerca.setText("Acerca de");
        mAyuda.add(macerca);

        menu.add(mAyuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cARarezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cARarezaActionPerformed
        if (cARareza.getSelectedIndex() == 1) {
            rareza = "comun";
        } else if (cARareza.getSelectedIndex() == 2) {
            rareza = "infrecuente";
        } else if (cARareza.getSelectedIndex() == 3) {
            rareza = "rara";
        } else if (cARareza.getSelectedIndex() == 4) {
            rareza = "mitica";
        }
    }//GEN-LAST:event_cARarezaActionPerformed

    private void cBTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBTipoActionPerformed
        if (cBTipo.getSelectedIndex() == 1) {
             tipo = "artefacto";
        } else if (cBTipo.getSelectedIndex() == 2) {
            tipo = "criatura";
        } else if (cBTipo.getSelectedIndex() == 3) {
            tipo = "conjuro";
        } else if (cBTipo.getSelectedIndex() == 4) {
            tipo = "encantamiento";
        } else if (cBTipo.getSelectedIndex() == 5) {
            tipo = "instantaneo";
        } else if (cBTipo.getSelectedIndex() == 6) {
            tipo = "tierra";
        }
    }//GEN-LAST:event_cBTipoActionPerformed

    private void cETipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cETipoActionPerformed
        if (cETipo.getSelectedIndex() == 0) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
        } else if (cETipo.getSelectedIndex() == 1) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            tipo = "artefacto";
        } else if (cETipo.getSelectedIndex() == 2) {
            eEFuerza.setEnabled(true);
            cEFuerza.setEnabled(true);
            eEDefensa.setEnabled(true);
            cEDefensa.setEnabled(true);
            tipo = "criatura";
        } else if (cETipo.getSelectedIndex() == 3) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            tipo = "conjuro";
        } else if (cETipo.getSelectedIndex() == 4) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            tipo = "encantamiento";
        } else if (cETipo.getSelectedIndex() == 5) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            tipo = "instantaneo";
        } else if (cETipo.getSelectedIndex() == 6) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            tipo = "tierra";
        }
    }//GEN-LAST:event_cETipoActionPerformed

    private void cATipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cATipoActionPerformed
        if (cATipo.getSelectedIndex() == 0) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
        } else if (cATipo.getSelectedIndex() == 1) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            tipo = "artefacto";
        } else if (cATipo.getSelectedIndex() == 2) {
            eAFuerza.setEnabled(true);
            cAFuerza.setEnabled(true);
            eADefensa.setEnabled(true);
            cADefensa.setEnabled(true);
            tipo = "criatura";
        } else if (cATipo.getSelectedIndex() == 3) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            tipo = "conjuro";
        } else if (cATipo.getSelectedIndex() == 4) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            tipo = "encantamiento";
        } else if (cATipo.getSelectedIndex() == 5) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            tipo = "instantaneo";
        } else if (cATipo.getSelectedIndex() == 6) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            tipo = "tierra";
        }
    }//GEN-LAST:event_cATipoActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
        nombre = tANombre.getText();
        habilidad = tAhabilidad.getText();
        cmc =Integer.parseInt(tACmc.getText());
        Metodos.insertar(nombre, tipo, rareza, habilidad, cmc, color, fuerza, defensa);
    }//GEN-LAST:event_bAñadirActionPerformed

    private void bVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisualizarActionPerformed
        //actualiza los datos de la tabla realizando una consulta a la base de datos
        String[] columNames = {"Nombre" ,"Tipo","Rareza","Habilidad"};
        dtCartas = con.Select_Cartas();
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtCartas,columNames);
        tabla.setModel(datos);
    }//GEN-LAST:event_bVisualizarActionPerformed

    private void rAAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAAzulActionPerformed
        if (rAAzul.isSelected() == true) {
            color = "azul";
            rABlanco.setSelected(false);
            rANegro.setSelected(false);
            rAVerde.setSelected(false);
            rARojo.setSelected(false);
            rAIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rAAzulActionPerformed

    private void rABlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rABlancoActionPerformed
        if (rABlanco.isSelected() == true) {
            color = "blanco";
            rAAzul.setSelected(false);
            rANegro.setSelected(false);
            rAVerde.setSelected(false);
            rARojo.setSelected(false);
            rAIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rABlancoActionPerformed

    private void rANegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rANegroActionPerformed
        if (rANegro.isSelected()==true){
            color = "negro";
            rABlanco.setSelected(false);
            rAAzul.setSelected(false);
            rAVerde.setSelected(false);
            rARojo.setSelected(false);
            rAIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rANegroActionPerformed

    private void rAVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAVerdeActionPerformed
        if (rAVerde.isSelected()==true){
            color = "verde";
            rABlanco.setSelected(false);
            rAAzul.setSelected(false);
            rANegro.setSelected(false);
            rARojo.setSelected(false);
            rAIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rAVerdeActionPerformed

    private void rAIncoloroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAIncoloroActionPerformed
        if (rAIncoloro.isSelected()==true){
            color = "incoloro";
            rABlanco.setSelected(false);
            rAAzul.setSelected(false);
            rANegro.setSelected(false);
            rARojo.setSelected(false);
            rAVerde.setSelected(false);
        }
    }//GEN-LAST:event_rAIncoloroActionPerformed

    private void rARojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rARojoActionPerformed
        if (rARojo.isSelected()==true){
            color = "rojo";
            rABlanco.setSelected(false);
            rAAzul.setSelected(false);
            rANegro.setSelected(false);
            rAIncoloro.setSelected(false);
            rAVerde.setSelected(false);
        }
    }//GEN-LAST:event_rARojoActionPerformed

    private void cAFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAFuerzaActionPerformed
        if (cAFuerza.getSelectedIndex() == 1) {
            fuerza = -1;
        } else if (cAFuerza.getSelectedIndex() == 2) {
            fuerza = 0;
        } else if (cAFuerza.getSelectedIndex() == 3) {
            fuerza = 1;
        } else if (cAFuerza.getSelectedIndex() == 4) {
            fuerza = 2;
        } else if (cAFuerza.getSelectedIndex() == 5) {
            fuerza = 3;
        } else if (cAFuerza.getSelectedIndex() == 6) {
            fuerza = 4;
        } else if (cAFuerza.getSelectedIndex() == 7) {
            fuerza = 5;
        } else if (cAFuerza.getSelectedIndex() == 8) {
            fuerza = 6;
        } else if (cAFuerza.getSelectedIndex() == 9) {
            fuerza = 7;
        } else if (cAFuerza.getSelectedIndex() == 10) {
            fuerza = 8;
        } else if (cAFuerza.getSelectedIndex() == 11) {
            fuerza = 9;
        } else if (cAFuerza.getSelectedIndex() == 12) {
            fuerza = 10;
        } else if (cAFuerza.getSelectedIndex() == 13) {
            fuerza = 11;
        } else if (cAFuerza.getSelectedIndex() == 14) {
            fuerza = 12;
        } else if (cAFuerza.getSelectedIndex() == 15) {
            fuerza = 13;
        } else if (cAFuerza.getSelectedIndex() == 16) {
            fuerza = 14;
        } else if (cAFuerza.getSelectedIndex() == 17) {
            fuerza = 15;
        }
    }//GEN-LAST:event_cAFuerzaActionPerformed

    private void cADefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cADefensaActionPerformed
        if (cADefensa.getSelectedIndex() == 1) {
            defensa = -1;
        } else if (cADefensa.getSelectedIndex() == 2) {
            defensa = 0;
        } else if (cADefensa.getSelectedIndex() == 3) {
            defensa = 1;
        } else if (cADefensa.getSelectedIndex() == 4) {
            defensa = 2;
        } else if (cADefensa.getSelectedIndex() == 5) {
            defensa = 3;
        } else if (cADefensa.getSelectedIndex() == 6) {
            defensa = 4;
        } else if (cADefensa.getSelectedIndex() == 7) {
            defensa = 5;
        } else if (cADefensa.getSelectedIndex() == 8) {
            defensa = 6;
        } else if (cADefensa.getSelectedIndex() == 9) {
            defensa = 7;
        } else if (cADefensa.getSelectedIndex() == 10) {
            defensa = 8;
        } else if (cADefensa.getSelectedIndex() == 11) {
            defensa = 9;
        } else if (cADefensa.getSelectedIndex() == 12) {
            defensa = 10;
        } else if (cADefensa.getSelectedIndex() == 13) {
            defensa = 11;
        } else if (cADefensa.getSelectedIndex() == 14) {
            defensa = 12;
        } else if (cADefensa.getSelectedIndex() == 15) {
            defensa = 13;
        } else if (cADefensa.getSelectedIndex() == 16) {
            defensa = 14;
        } else if (cADefensa.getSelectedIndex() == 17) {
            defensa = 15;
        }
    }//GEN-LAST:event_cADefensaActionPerformed

    private void cENombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cENombreActionPerformed
       /* dtCartas = con.Select_Cartas();
        String[] columNames = {"Nombre" ,"Tipo","Rareza","Habilidad"};
         for (int i = 0; i < dtCartas.length; i++) {
                for (int j = 0; j < dtCartas[i].length; j++) {
                    cENombre.setSelectedItem(dtCartas[i][j]);
                }
            }*/
        //actualiza los datos de la tabla realizando una consulta a la base de datos
        String[] columNames = {"Nombre" ,"Tipo","Rareza","Habilidad"};
        dtCartas = con.Select_Cartas();
        // se colocan los datos en la tabla
        
        DefaultTableModel datos = new DefaultTableModel(dtCartas,columNames);
        tabla.setModel(datos);
    }//GEN-LAST:event_cENombreActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        nombre = tENombre.getText();
        habilidad = tEhabilidad.getText();
        cmc =Integer.parseInt(tECmc.getText());
        nombreViejo = cENombre.getSelectedItem().toString();
        Metodos.editar(nombreViejo,nombre, tipo, rareza, habilidad, cmc, color, fuerza, defensa);
    }//GEN-LAST:event_bEditarActionPerformed

    private void cERarezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cERarezaActionPerformed
        if (cERareza.getSelectedIndex() == 1) {
            rareza = "comun";
        } else if (cERareza.getSelectedIndex() == 2) {
            rareza = "infrecuente";
        } else if (cERareza.getSelectedIndex() == 3) {
            rareza = "rara";
        } else if (cERareza.getSelectedIndex() == 4) {
            rareza = "mitica";
        }
    }//GEN-LAST:event_cERarezaActionPerformed

    private void cEFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEFuerzaActionPerformed
        if (cEFuerza.getSelectedIndex() == 1) {
            fuerza = -1;
        } else if (cEFuerza.getSelectedIndex() == 2) {
            fuerza = 0;
        } else if (cEFuerza.getSelectedIndex() == 3) {
            fuerza = 1;
        } else if (cEFuerza.getSelectedIndex() == 4) {
            fuerza = 2;
        } else if (cEFuerza.getSelectedIndex() == 5) {
            fuerza = 3;
        } else if (cEFuerza.getSelectedIndex() == 6) {
            fuerza = 4;
        } else if (cEFuerza.getSelectedIndex() == 7) {
            fuerza = 5;
        } else if (cEFuerza.getSelectedIndex() == 8) {
            fuerza = 6;
        } else if (cEFuerza.getSelectedIndex() == 9) {
            fuerza = 7;
        } else if (cEFuerza.getSelectedIndex() == 10) {
            fuerza = 8;
        } else if (cEFuerza.getSelectedIndex() == 11) {
            fuerza = 9;
        } else if (cEFuerza.getSelectedIndex() == 12) {
            fuerza = 10;
        } else if (cEFuerza.getSelectedIndex() == 13) {
            fuerza = 11;
        } else if (cEFuerza.getSelectedIndex() == 14) {
            fuerza = 12;
        } else if (cEFuerza.getSelectedIndex() == 15) {
            fuerza = 13;
        } else if (cEFuerza.getSelectedIndex() == 16) {
            fuerza = 14;
        } else if (cEFuerza.getSelectedIndex() == 17) {
            fuerza = 15;
        }
    }//GEN-LAST:event_cEFuerzaActionPerformed

    private void cEDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEDefensaActionPerformed
        if (cEDefensa.getSelectedIndex() == 1) {
            defensa = -1;
        } else if (cEDefensa.getSelectedIndex() == 2) {
            defensa = 0;
        } else if (cEDefensa.getSelectedIndex() == 3) {
            defensa = 1;
        } else if (cEDefensa.getSelectedIndex() == 4) {
            defensa = 2;
        } else if (cEDefensa.getSelectedIndex() == 5) {
            defensa = 3;
        } else if (cEDefensa.getSelectedIndex() == 6) {
            defensa = 4;
        } else if (cEDefensa.getSelectedIndex() == 7) {
            defensa = 5;
        } else if (cEDefensa.getSelectedIndex() == 8) {
            defensa = 6;
        } else if (cEDefensa.getSelectedIndex() == 9) {
            defensa = 7;
        } else if (cEDefensa.getSelectedIndex() == 10) {
            defensa = 8;
        } else if (cEDefensa.getSelectedIndex() == 11) {
            defensa = 9;
        } else if (cEDefensa.getSelectedIndex() == 12) {
            defensa = 10;
        } else if (cEDefensa.getSelectedIndex() == 13) {
            defensa = 11;
        } else if (cEDefensa.getSelectedIndex() == 14) {
            defensa = 12;
        } else if (cEDefensa.getSelectedIndex() == 15) {
            defensa = 13;
        } else if (cEDefensa.getSelectedIndex() == 16) {
            defensa = 14;
        } else if (cEDefensa.getSelectedIndex() == 17) {
            defensa = 15;
        }
    }//GEN-LAST:event_cEDefensaActionPerformed

    private void cBRarezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBRarezaActionPerformed
        if (cBRareza.getSelectedIndex() == 1) {
            rareza = "comun";
        } else if (cBRareza.getSelectedIndex() == 2) {
            rareza = "infrecuente";
        } else if (cBRareza.getSelectedIndex() == 3) {
            rareza = "rara";
        } else if (cBRareza.getSelectedIndex() == 4) {
            rareza = "mitica";
        }
    }//GEN-LAST:event_cBRarezaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bVisualizar;
    private javax.swing.JComboBox cADefensa;
    private javax.swing.JComboBox cAFuerza;
    private javax.swing.JComboBox cARareza;
    private javax.swing.JComboBox cATipo;
    private javax.swing.JComboBox cBRareza;
    private javax.swing.JComboBox cBTipo;
    private javax.swing.JComboBox cEDefensa;
    private javax.swing.JComboBox cEFuerza;
    private javax.swing.JComboBox cENombre;
    private javax.swing.JComboBox cERareza;
    private javax.swing.JComboBox cETipo;
    private javax.swing.JLabel eADefensa;
    private javax.swing.JLabel eAFuerza;
    private javax.swing.JLabel eEDefensa;
    private javax.swing.JLabel eEFuerza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenuItem mAñadir;
    private javax.swing.JMenuItem mBuscar;
    private javax.swing.JMenuItem mEditar;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuItem mVisualizar;
    private javax.swing.JMenuItem macerca;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPanel pAñadir;
    private javax.swing.JPanel pBuscar;
    private javax.swing.JPanel pEditar;
    private javax.swing.JPanel pInicial;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JPanel pVisualizar;
    private javax.swing.JTabbedPane paneles;
    private javax.swing.JRadioButton rAAzul;
    private javax.swing.JRadioButton rABlanco;
    private javax.swing.JRadioButton rAIncoloro;
    private javax.swing.JRadioButton rANegro;
    private javax.swing.JRadioButton rARojo;
    private javax.swing.JRadioButton rAVerde;
    private javax.swing.JRadioButton rEAzul;
    private javax.swing.JRadioButton rEBlanco;
    private javax.swing.JRadioButton rEIncoloro;
    private javax.swing.JRadioButton rENegro;
    private javax.swing.JRadioButton rERojo;
    private javax.swing.JRadioButton rEVerde;
    private javax.swing.JTextField tACmc;
    private javax.swing.JTextField tANombre;
    private javax.swing.JTextField tAhabilidad;
    private javax.swing.JTextField tAimagen;
    private javax.swing.JTextField tBNombre;
    private javax.swing.JTextField tBhabilidad;
    private javax.swing.JTextField tECmc;
    private javax.swing.JTextField tENombre;
    private javax.swing.JTextField tEhabilidad;
    private javax.swing.JTextField tEimagen;
    private javax.swing.JTable tabla;
    private javax.swing.JDialog vAcerca;
    private javax.swing.JDialog vAñadir;
    private javax.swing.JFrame vBuscar;
    private javax.swing.JDialog vEditar;
    // End of variables declaration//GEN-END:variables
}
