/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Buscador;

import Objetos.Cartas;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DAM1_16
 */
public class Principal extends javax.swing.JFrame {

    private Cartas c;
    private Conexion con = new Conexion();
    private Metodos met = new Metodos();
    private String nombre = null, color = null, rareza = null, habilidad = null, tipo = null, nombreViejo = null, tipoViejo = null;
    private int cmc = 0, fuerza = -1, defensa = -1;
    private Object[][] dtCartas;

    //Añade icono al jframe
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().
                getImage(ClassLoader.getSystemResource("Imagenes/icono.png"));

        return retValue;
    }

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        con.GetConnection();
        this.cENombre.setModel(con.LlenarComboBox());
        this.cBNombre.setModel(con.LlenarComboBox());
        //dtCartas=con.SelectIns("4");
        //System.out.println(dtCartas[0][1].toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vBuscar = new javax.swing.JFrame();
        bDefensa = new javax.swing.JLabel();
        bFuerza = new javax.swing.JLabel();
        bColor = new javax.swing.JLabel();
        bCmc = new javax.swing.JLabel();
        bRareza = new javax.swing.JLabel();
        bTipo = new javax.swing.JLabel();
        bNombre = new javax.swing.JLabel();
        separador = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bHabilidad = new javax.swing.JTextArea();
        vAñadir = new javax.swing.JDialog();
        tAñadido = new javax.swing.JLabel();
        vEditar = new javax.swing.JDialog();
        tEAñadido = new javax.swing.JLabel();
        vAcerca = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pInicial = new javax.swing.JPanel();
        paneles = new javax.swing.JTabbedPane();
        pPrincipal = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pVisualizar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bVisualizar = new javax.swing.JButton();
        pAñadir = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tANombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rAAzul = new javax.swing.JRadioButton();
        rABlanco = new javax.swing.JRadioButton();
        rANegro = new javax.swing.JRadioButton();
        rARojo = new javax.swing.JRadioButton();
        rAVerde = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        cATipo = new javax.swing.JComboBox();
        cARareza = new javax.swing.JComboBox();
        eACmc = new javax.swing.JLabel();
        tACmc = new javax.swing.JTextField();
        eAFuerza = new javax.swing.JLabel();
        eADefensa = new javax.swing.JLabel();
        cAFuerza = new javax.swing.JComboBox();
        cADefensa = new javax.swing.JComboBox();
        bAñadir = new javax.swing.JButton();
        rAIncoloro = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tAhabilidad = new javax.swing.JTextArea();
        pEditar = new javax.swing.JPanel();
        bEditar = new javax.swing.JButton();
        cEDefensa = new javax.swing.JComboBox();
        eEDefensa = new javax.swing.JLabel();
        eEFuerza = new javax.swing.JLabel();
        cEFuerza = new javax.swing.JComboBox();
        eECmc = new javax.swing.JLabel();
        tECmc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cETipo = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cERareza = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        tENombre = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cENombre = new javax.swing.JComboBox();
        rEAzul = new javax.swing.JRadioButton();
        rERojo = new javax.swing.JRadioButton();
        rEBlanco = new javax.swing.JRadioButton();
        rEVerde = new javax.swing.JRadioButton();
        rENegro = new javax.swing.JRadioButton();
        rEIncoloro = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tEhabilidad = new javax.swing.JTextArea();
        pBuscar = new javax.swing.JPanel();
        bBuscar = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        cBTipo = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        cBNombre = new javax.swing.JComboBox();
        menu = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenuItem();
        mAyuda = new javax.swing.JMenu();
        macerca = new javax.swing.JMenuItem();

        vBuscar.setIconImage(getIconImage());
        vBuscar.setMinimumSize(new java.awt.Dimension(535, 350));

        bDefensa.setText("Def");

        bFuerza.setText("Fue");

        bColor.setText("Color");

        bCmc.setText("Cmc");

        bRareza.setText("Rareza");

        bTipo.setText("Tipo");

        bNombre.setText("Nombre");

        separador.setText("/");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Image1.jpg"))); // NOI18N

        bHabilidad.setEditable(false);
        bHabilidad.setColumns(20);
        bHabilidad.setRows(5);
        bHabilidad.setAutoscrolls(false);
        jScrollPane3.setViewportView(bHabilidad);

        javax.swing.GroupLayout vBuscarLayout = new javax.swing.GroupLayout(vBuscar.getContentPane());
        vBuscar.getContentPane().setLayout(vBuscarLayout);
        vBuscarLayout.setHorizontalGroup(
            vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGroup(vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vBuscarLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(bNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bCmc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bColor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vBuscarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vBuscarLayout.createSequentialGroup()
                                .addComponent(bTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(vBuscarLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(bFuerza)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(separador)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bDefensa))
                                    .addComponent(bRareza, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        vBuscarLayout.setVerticalGroup(
            vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vBuscarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bNombre)
                            .addComponent(bCmc)
                            .addComponent(bColor))
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bTipo)
                            .addComponent(bRareza))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(vBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(separador)
                            .addComponent(bDefensa)
                            .addComponent(bFuerza)))
                    .addComponent(jLabel12))
                .addContainerGap(3029, Short.MAX_VALUE))
        );

        vAñadir.setIconImage(getIconImage());
        vAñadir.setMinimumSize(new java.awt.Dimension(357, 100));

        tAñadido.setFont(new java.awt.Font("Magic:the Gathering", 0, 24)); // NOI18N
        tAñadido.setText("Carta insertada correctamente.");

        javax.swing.GroupLayout vAñadirLayout = new javax.swing.GroupLayout(vAñadir.getContentPane());
        vAñadir.getContentPane().setLayout(vAñadirLayout);
        vAñadirLayout.setHorizontalGroup(
            vAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vAñadirLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tAñadido)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        vAñadirLayout.setVerticalGroup(
            vAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vAñadirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tAñadido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vEditar.setIconImage(getIconImage());
        vEditar.setMinimumSize(new java.awt.Dimension(220, 100));

        tEAñadido.setFont(new java.awt.Font("Magic:the Gathering", 0, 24)); // NOI18N
        tEAñadido.setText("Carta modificada.");

        javax.swing.GroupLayout vEditarLayout = new javax.swing.GroupLayout(vEditar.getContentPane());
        vEditar.getContentPane().setLayout(vEditarLayout);
        vEditarLayout.setHorizontalGroup(
            vEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vEditarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(tEAñadido, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        vEditarLayout.setVerticalGroup(
            vEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tEAñadido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vAcerca.setIconImage(null);
        vAcerca.setMinimumSize(new java.awt.Dimension(412, 313));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(102, 102, 102));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Magic:the Gathering", 0, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(0, 0, 153));
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\tBuscadorMTG v1.0\n\t\nDesarroyadores:\n\nYago Casal Quintas.\nMiguel Angel Perez Silva.\nRaul Saa Perez.\n\n\n\n\nCopyright all right reserved to Project666 Entertiment\n\n");
        jTextArea1.setAutoscrolls(false);
        jTextArea1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)));
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout vAcercaLayout = new javax.swing.GroupLayout(vAcerca.getContentPane());
        vAcerca.getContentPane().setLayout(vAcercaLayout);
        vAcercaLayout.setHorizontalGroup(
            vAcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vAcercaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );
        vAcercaLayout.setVerticalGroup(
            vAcercaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vAcercaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BuscadorMTG");
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(700, 525));
        setPreferredSize(new java.awt.Dimension(700, 525));
        setResizable(false);

        pInicial.setMinimumSize(new java.awt.Dimension(700, 680));
        pInicial.setPreferredSize(new java.awt.Dimension(700, 680));

        paneles.setMinimumSize(new java.awt.Dimension(700, 680));
        paneles.setPreferredSize(new java.awt.Dimension(700, 680));

        pPrincipal.setMinimumSize(new java.awt.Dimension(670, 670));
        pPrincipal.setPreferredSize(new java.awt.Dimension(670, 670));

        jLabel34.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        jLabel34.setText("Bienvenido a nuestra base de datos de cartas de Magic the Gathering");

        jLabel35.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        jLabel35.setText("Esperamos que tengas una grata experiencia.");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/magic_the_gathering_1.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 8)); // NOI18N
        jLabel15.setText("Esta aplicacion no esta producida, afiliada o apoyada por Wizards of the Coast®");

        javax.swing.GroupLayout pPrincipalLayout = new javax.swing.GroupLayout(pPrincipal);
        pPrincipal.setLayout(pPrincipalLayout);
        pPrincipalLayout.setHorizontalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGroup(pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15))
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(jLabel11))
                    .addGroup(pPrincipalLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel34)))
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel35)
                .addGap(177, 177, 177))
        );
        pPrincipalLayout.setVerticalGroup(
            pPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pPrincipalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addGap(74, 74, 74)
                .addComponent(jLabel15)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        paneles.addTab("Principal", pPrincipal);

        pVisualizar.setMinimumSize(new java.awt.Dimension(670, 670));
        pVisualizar.setPreferredSize(new java.awt.Dimension(670, 670));

        tabla.setFont(new java.awt.Font("Magic:the Gathering", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Tipo", "Rareza", "Habilidad"
            }
        ));
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabla);

        jLabel1.setText("Bienvenido al visualizador de nuestro programa, presione el siguiente boton para visualizar ");

        jLabel2.setText("la lista completa de cartas almacenada en nuestro servidor.");

        bVisualizar.setText("Visualizar cartas");
        bVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pVisualizarLayout = new javax.swing.GroupLayout(pVisualizar);
        pVisualizar.setLayout(pVisualizarLayout);
        pVisualizarLayout.setHorizontalGroup(
            pVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVisualizarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(pVisualizarLayout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(bVisualizar)))
                .addContainerGap(236, Short.MAX_VALUE))
            .addGroup(pVisualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                .addContainerGap())
        );
        pVisualizarLayout.setVerticalGroup(
            pVisualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pVisualizarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bVisualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(271, 271, 271))
        );

        paneles.addTab("Visualizar lista", pVisualizar);

        pAñadir.setMinimumSize(new java.awt.Dimension(670, 670));
        pAñadir.setPreferredSize(new java.awt.Dimension(670, 670));

        jLabel3.setText("En esta pestaña puedes añadir una carta nueva a nuestra base de datos, para ello cubre el");

        jLabel4.setText("siguiente formulario y presiona añadir:");

        jLabel5.setText("Nombre:");

        tANombre.setFont(new java.awt.Font("Magic:the Gathering", 0, 16)); // NOI18N

        jLabel6.setText("Tipo:");

        jLabel7.setText("Habilidad:");

        jLabel8.setText("Color:");

        rAAzul.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rAAzul.setForeground(new java.awt.Color(0, 51, 204));
        rAAzul.setText(" Azul +");
        rAAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAAzulActionPerformed(evt);
            }
        });

        rABlanco.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rABlanco.setForeground(new java.awt.Color(255, 255, 204));
        rABlanco.setText("Blanco @ ");
        rABlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rABlancoActionPerformed(evt);
            }
        });

        rANegro.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rANegro.setText(" Negro =");
        rANegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rANegroActionPerformed(evt);
            }
        });

        rARojo.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rARojo.setForeground(new java.awt.Color(255, 0, 0));
        rARojo.setText(" Rojo <");
        rARojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rARojoActionPerformed(evt);
            }
        });

        rAVerde.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rAVerde.setForeground(new java.awt.Color(51, 130, 60));
        rAVerde.setText(" Verde >");
        rAVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAVerdeActionPerformed(evt);
            }
        });

        jLabel9.setText("Rareza:");

        cATipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona un tipo", "Artefacto", "Criatura", "Conjuro", "Encantamiento", "Instantaneo", "Tierra" }));
        cATipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cATipoActionPerformed(evt);
            }
        });

        cARareza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una rareza", "Comun", "Infrecuente", "Rara", "Rara Mitica" }));
        cARareza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cARarezaActionPerformed(evt);
            }
        });

        eACmc.setText("Coste de Mana Convertido:");

        tACmc.setFont(new java.awt.Font("Magic:the Gathering", 0, 16)); // NOI18N
        tACmc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tACmcActionPerformed(evt);
            }
        });

        eAFuerza.setText("Fuerza:");
        eAFuerza.setEnabled(false);

        eADefensa.setText("Defensa:");
        eADefensa.setEnabled(false);

        cAFuerza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una fuerza", "-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cAFuerza.setEnabled(false);
        cAFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cAFuerzaActionPerformed(evt);
            }
        });

        cADefensa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una defensa", "-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cADefensa.setEnabled(false);
        cADefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cADefensaActionPerformed(evt);
            }
        });

        bAñadir.setText("Añadir");
        bAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAñadirActionPerformed(evt);
            }
        });

        rAIncoloro.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rAIncoloro.setForeground(new java.awt.Color(102, 102, 102));
        rAIncoloro.setText("Incoloro");
        rAIncoloro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rAIncoloroActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner2.jpg"))); // NOI18N

        tAhabilidad.setColumns(20);
        tAhabilidad.setFont(new java.awt.Font("Magic:the Gathering", 0, 16)); // NOI18N
        tAhabilidad.setRows(5);
        tAhabilidad.setMaximumSize(new java.awt.Dimension(164, 94));
        tAhabilidad.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane4.setViewportView(tAhabilidad);

        javax.swing.GroupLayout pAñadirLayout = new javax.swing.GroupLayout(pAñadir);
        pAñadir.setLayout(pAñadirLayout);
        pAñadirLayout.setHorizontalGroup(
            pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAñadirLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(pAñadirLayout.createSequentialGroup()
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bAñadir)
                            .addGroup(pAñadirLayout.createSequentialGroup()
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAñadirLayout.createSequentialGroup()
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cATipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tANombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel8)
                                    .addGroup(pAñadirLayout.createSequentialGroup()
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rABlanco)
                                            .addComponent(rANegro)
                                            .addComponent(rAAzul))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rARojo)
                                            .addComponent(rAIncoloro)
                                            .addComponent(rAVerde)))
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAñadirLayout.createSequentialGroup()
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(eAFuerza)
                                            .addComponent(eADefensa))
                                        .addGap(23, 23, 23)
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cADefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cAFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAñadirLayout.createSequentialGroup()
                                            .addComponent(eACmc)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tACmc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAñadirLayout.createSequentialGroup()
                                            .addGap(1, 1, 1)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cARareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAñadirLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jScrollPane4))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pAñadirLayout.setVerticalGroup(
            pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAñadirLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAñadirLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pAñadirLayout.createSequentialGroup()
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(tANombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addGap(58, 58, 58))
                            .addGroup(pAñadirLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pAñadirLayout.createSequentialGroup()
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cATipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rAAzul)
                                    .addComponent(rARojo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rABlanco)
                                    .addComponent(rAVerde))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rANegro)
                                    .addComponent(rAIncoloro)))
                            .addGroup(pAñadirLayout.createSequentialGroup()
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(cARareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eACmc)
                                    .addGroup(pAñadirLayout.createSequentialGroup()
                                        .addComponent(tACmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(eAFuerza)
                                            .addComponent(cAFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(21, 21, 21)
                                .addGroup(pAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eADefensa)
                                    .addComponent(cADefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)
                        .addComponent(bAñadir))
                    .addComponent(jLabel14))
                .addContainerGap(259, Short.MAX_VALUE))
        );

        paneles.addTab("Añadir carta", pAñadir);

        pEditar.setMinimumSize(new java.awt.Dimension(670, 670));
        pEditar.setPreferredSize(new java.awt.Dimension(670, 670));

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        cEDefensa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una defensa", "-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cEDefensa.setEnabled(false);
        cEDefensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEDefensaActionPerformed(evt);
            }
        });

        eEDefensa.setText("Defensa:");
        eEDefensa.setEnabled(false);

        eEFuerza.setText("Fuerza:");
        eEFuerza.setEnabled(false);

        cEFuerza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una fuerza", "-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        cEFuerza.setEnabled(false);
        cEFuerza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cEFuerzaActionPerformed(evt);
            }
        });

        eECmc.setText("Coste de Mana Convertido:");

        tECmc.setFont(new java.awt.Font("Magic:the Gathering", 0, 16)); // NOI18N

        jLabel16.setText("Color:");

        jLabel17.setText("Tipo:");

        cETipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona un tipo", "Artefacto", "Criatura", "Conjuro", "Encantamiento", "Instantaneo", "Tierra" }));
        cETipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cETipoActionPerformed(evt);
            }
        });

        jLabel18.setText("Rareza:");

        cERareza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona una rareza", "Comun", "Infrecuente", "Rara", "Rara Mitica" }));
        cERareza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cERarezaActionPerformed(evt);
            }
        });

        jLabel19.setText("Habilidad:");

        tENombre.setFont(new java.awt.Font("Magic:the Gathering", 0, 16)); // NOI18N

        jLabel20.setText("Nombre:");

        jLabel21.setText("formulario y presiona editar:");

        jLabel22.setText("En esta pestaña puedes editar una carta ya existente, para ello cubre el siguiente");

        jLabel23.setText("Indica la carta a editar:");

        cENombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cENombreActionPerformed(evt);
            }
        });

        rEAzul.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rEAzul.setForeground(new java.awt.Color(0, 51, 204));
        rEAzul.setText(" Azul +");
        rEAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEAzulActionPerformed(evt);
            }
        });

        rERojo.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rERojo.setForeground(new java.awt.Color(255, 0, 0));
        rERojo.setText("Rojo < ");
        rERojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rERojoActionPerformed(evt);
            }
        });

        rEBlanco.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rEBlanco.setForeground(new java.awt.Color(255, 255, 204));
        rEBlanco.setText("Blanco @ ");
        rEBlanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEBlancoActionPerformed(evt);
            }
        });

        rEVerde.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rEVerde.setForeground(new java.awt.Color(51, 130, 60));
        rEVerde.setText("Verde > ");
        rEVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEVerdeActionPerformed(evt);
            }
        });

        rENegro.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rENegro.setText(" Negro =");
        rENegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rENegroActionPerformed(evt);
            }
        });

        rEIncoloro.setFont(new java.awt.Font("Magic:the Gathering", 0, 18)); // NOI18N
        rEIncoloro.setForeground(new java.awt.Color(102, 102, 102));
        rEIncoloro.setText("Incoloro");
        rEIncoloro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rEIncoloroActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/banner1.jpg"))); // NOI18N

        tEhabilidad.setColumns(20);
        tEhabilidad.setFont(new java.awt.Font("Magic:the Gathering", 0, 16)); // NOI18N
        tEhabilidad.setRows(5);
        tEhabilidad.setMaximumSize(new java.awt.Dimension(164, 94));
        tEhabilidad.setMinimumSize(new java.awt.Dimension(164, 94));
        jScrollPane5.setViewportView(tEhabilidad);

        javax.swing.GroupLayout pEditarLayout = new javax.swing.GroupLayout(pEditar);
        pEditar.setLayout(pEditarLayout);
        pEditarLayout.setHorizontalGroup(
            pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEditarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEditarLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pEditarLayout.createSequentialGroup()
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21)
                            .addGroup(pEditarLayout.createSequentialGroup()
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pEditarLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cETipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel16)
                                    .addGroup(pEditarLayout.createSequentialGroup()
                                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rEBlanco)
                                            .addComponent(rENegro)
                                            .addComponent(rEAzul))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rERojo)
                                            .addComponent(rEIncoloro)
                                            .addComponent(rEVerde))))
                                .addGap(18, 18, 18)
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pEditarLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cERareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pEditarLayout.createSequentialGroup()
                                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(eEFuerza)
                                            .addComponent(eEDefensa))
                                        .addGap(23, 23, 23)
                                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cEDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cEFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(pEditarLayout.createSequentialGroup()
                                        .addComponent(eECmc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tECmc, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(bEditar)
                            .addGroup(pEditarLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tENombre, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pEditarLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cENombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(50, 50, 50))))
        );
        pEditarLayout.setVerticalGroup(
            pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pEditarLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(cENombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(tENombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel19))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cERareza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(cETipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18)))
                        .addGap(21, 21, 21)
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(eECmc)
                            .addComponent(tECmc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pEditarLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eEFuerza)
                                    .addComponent(cEFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eEDefensa)
                                    .addComponent(cEDefensa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pEditarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rEAzul)
                                    .addComponent(rERojo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rEBlanco)
                                    .addComponent(rEVerde))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rENegro)
                                    .addComponent(rEIncoloro))))
                        .addGap(18, 18, 18)
                        .addComponent(bEditar))
                    .addComponent(jLabel10))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        paneles.addTab("Editar carta", pEditar);

        pBuscar.setMinimumSize(new java.awt.Dimension(670, 670));
        pBuscar.setPreferredSize(new java.awt.Dimension(670, 670));

        bBuscar.setText("Buscar");
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        jLabel25.setText("Tipo:");

        jLabel26.setText("Nombre:");

        jLabel27.setText("siguiente formulario y presiona el boton para buscar:");

        jLabel28.setText("En esta pestaña puedes buscar una carta de nuestra base de datos, para ello cubre el");

        cBTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecciona un tipo", "Artefacto", "Criatura", "Conjuro", "Encantamiento", "Instantaneo", "Tierra" }));
        cBTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBTipoActionPerformed(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Banner-Magic_the_Gathering.jpg"))); // NOI18N

        cBNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBuscarLayout = new javax.swing.GroupLayout(pBuscar);
        pBuscar.setLayout(pBuscarLayout);
        pBuscarLayout.setHorizontalGroup(
            pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBuscarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bBuscar)
                        .addComponent(jLabel27))
                    .addGroup(pBuscarLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pBuscarLayout.createSequentialGroup()
                                .addComponent(cBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 132, Short.MAX_VALUE))
        );
        pBuscarLayout.setVerticalGroup(
            pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBuscarLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addGap(34, 34, 34)
                .addGroup(pBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel25)
                    .addComponent(cBTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cBNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(bBuscar)
                .addGap(36, 36, 36)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(386, Short.MAX_VALUE))
        );

        paneles.addTab("Buscar carta", pBuscar);

        javax.swing.GroupLayout pInicialLayout = new javax.swing.GroupLayout(pInicial);
        pInicial.setLayout(pInicialLayout);
        pInicialLayout.setHorizontalGroup(
            pInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInicialLayout.createSequentialGroup()
                .addComponent(paneles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pInicialLayout.setVerticalGroup(
            pInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pInicialLayout.createSequentialGroup()
                .addComponent(paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 233, Short.MAX_VALUE))
        );

        mArchivo.setText("Archivo");

        mSalir.setText("Salir");
        mSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mSalirActionPerformed(evt);
            }
        });
        mArchivo.add(mSalir);

        menu.add(mArchivo);

        mAyuda.setText("Ayuda");

        macerca.setText("Acerca de");
        macerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                macercaActionPerformed(evt);
            }
        });
        mAyuda.add(macerca);

        menu.add(mAyuda);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cARarezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cARarezaActionPerformed
        if (cARareza.getSelectedIndex() == 1) {
            rareza = "Comun";
        } else if (cARareza.getSelectedIndex() == 2) {
            rareza = "Infrecuente";
        } else if (cARareza.getSelectedIndex() == 3) {
            rareza = "Rara";
        } else if (cARareza.getSelectedIndex() == 4) {
            rareza = "Rara Mitica";
        }
    }//GEN-LAST:event_cARarezaActionPerformed

    private void cBTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBTipoActionPerformed
        if (cBTipo.getSelectedIndex() == 1) {
            tipo = "Artefacto";
        } else if (cBTipo.getSelectedIndex() == 2) {
            tipo = "Criatura";
        } else if (cBTipo.getSelectedIndex() == 3) {
            tipo = "Conjuro";
        } else if (cBTipo.getSelectedIndex() == 4) {
            tipo = "Encantamiento";
        } else if (cBTipo.getSelectedIndex() == 5) {
            tipo = "Instantaneo";
        } else if (cBTipo.getSelectedIndex() == 6) {
            tipo = "Tierra";
        }
    }//GEN-LAST:event_cBTipoActionPerformed

    private void cETipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cETipoActionPerformed
        if (cETipo.getSelectedIndex() == 0) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            eECmc.setEnabled(false);
            tECmc.setEnabled(false);
        } else if (cETipo.getSelectedIndex() == 1) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            eECmc.setEnabled(true);
            tECmc.setEnabled(true);
            tipo = "Artefacto";
        } else if (cETipo.getSelectedIndex() == 2) {
            eEFuerza.setEnabled(true);
            cEFuerza.setEnabled(true);
            eEDefensa.setEnabled(true);
            cEDefensa.setEnabled(true);
            eECmc.setEnabled(true);
            tECmc.setEnabled(true);
            tipo = "Criatura";
        } else if (cETipo.getSelectedIndex() == 3) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            eECmc.setEnabled(true);
            tECmc.setEnabled(true);
            tipo = "Conjuro";
        } else if (cETipo.getSelectedIndex() == 4) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            eECmc.setEnabled(true);
            tECmc.setEnabled(true);
            tipo = "Encantamiento";
        } else if (cETipo.getSelectedIndex() == 5) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            eECmc.setEnabled(true);
            tECmc.setEnabled(true);
            tipo = "Instantaneo";
        } else if (cETipo.getSelectedIndex() == 6) {
            eEFuerza.setEnabled(false);
            cEFuerza.setEnabled(false);
            eEDefensa.setEnabled(false);
            cEDefensa.setEnabled(false);
            eACmc.setEnabled(false);
            tACmc.setEnabled(false);
            tipo = "Tierra";
        }
    }//GEN-LAST:event_cETipoActionPerformed

    private void cATipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cATipoActionPerformed
        if (cATipo.getSelectedIndex() == 0) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            eACmc.setEnabled(false);
            tACmc.setEnabled(false);
        } else if (cATipo.getSelectedIndex() == 1) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            eACmc.setEnabled(true);
            tACmc.setEnabled(true);
            tipo = "Artefacto";
        } else if (cATipo.getSelectedIndex() == 2) {
            eAFuerza.setEnabled(true);
            cAFuerza.setEnabled(true);
            eADefensa.setEnabled(true);
            cADefensa.setEnabled(true);
            eACmc.setEnabled(true);
            tACmc.setEnabled(true);
            tipo = "Criatura";
        } else if (cATipo.getSelectedIndex() == 3) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            eACmc.setEnabled(true);
            tACmc.setEnabled(true);
            tipo = "Conjuro";
        } else if (cATipo.getSelectedIndex() == 4) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            eACmc.setEnabled(true);
            tACmc.setEnabled(true);
            tipo = "Encantamiento";
        } else if (cATipo.getSelectedIndex() == 5) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            eACmc.setEnabled(true);
            tACmc.setEnabled(true);
            tipo = "Instantaneo";
        } else if (cATipo.getSelectedIndex() == 6) {
            eAFuerza.setEnabled(false);
            cAFuerza.setEnabled(false);
            eADefensa.setEnabled(false);
            cADefensa.setEnabled(false);
            eACmc.setEnabled(false);
            tACmc.setEnabled(false);
            tipo = "Tierra";
        }
    }//GEN-LAST:event_cATipoActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        nombre = cBNombre.getSelectedItem().toString();
        if ("".equals(nombre) || tipo == null) {
            JOptionPane.showMessageDialog(null,"Los campos Nombre y Tipo son obligatorios.");
        } else {
            switch (tipo) {
                case "Instantaneo":
                    dtCartas = con.SelectIns(nombre);
                    if (dtCartas[0][0] != null){
                        bNombre.setText(dtCartas[0][0].toString());
                        bTipo.setText(dtCartas[0][1].toString());
                        bRareza.setText(dtCartas[0][2].toString());
                        bHabilidad.setText(dtCartas[0][3].toString());
                        bCmc.setText(Integer.toString(Integer.parseInt(dtCartas[0][4].toString())));
                        bColor.setText(dtCartas[0][5].toString());
                        bFuerza.setVisible(false);
                        bDefensa.setVisible(false);
                        separador.setVisible(false);
                        vBuscar.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "La carta indicada no se encuentra en nuestra base de datos");
                    }
                    break;
                case "Criatura":
                    dtCartas = con.SelectCria(nombre);
                    if (dtCartas[0][0] != null){
                    bNombre.setText(dtCartas[0][0].toString());
                    bTipo.setText(dtCartas[0][1].toString());
                    bRareza.setText(dtCartas[0][2].toString());
                    bHabilidad.setText(dtCartas[0][3].toString());
                    bCmc.setText(Integer.toString(Integer.parseInt(dtCartas[0][4].toString())));
                    bColor.setText(dtCartas[0][5].toString());
                    bFuerza.setText(Integer.toString(Integer.parseInt(dtCartas[0][6].toString())));
                    bDefensa.setText(Integer.toString(Integer.parseInt(dtCartas[0][7].toString())));
                    vBuscar.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "La carta indicada no se encuentra en nuestra base de datos");
                    }
                    break;
                case "Encantamiento":
                    dtCartas = con.SelectEnc(nombre);
                    if (dtCartas[0][0] != null){
                    bNombre.setText(dtCartas[0][0].toString());
                    bTipo.setText(dtCartas[0][1].toString());
                    bRareza.setText(dtCartas[0][2].toString());
                    bHabilidad.setText(dtCartas[0][3].toString());
                    bCmc.setText(Integer.toString(Integer.parseInt(dtCartas[0][4].toString())));
                    bColor.setText(dtCartas[0][5].toString());
                    bFuerza.setVisible(false);
                    bDefensa.setVisible(false);
                    separador.setVisible(false);
                    vBuscar.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "La carta indicada no se encuentra en nuestra base de datos");
                    }
                    break;
                case "Artefacto":
                    dtCartas = con.SelectArt(nombre);
                    if (dtCartas[0][0] != null){
                    bNombre.setText(dtCartas[0][0].toString());
                    bTipo.setText(dtCartas[0][1].toString());
                    bRareza.setText(dtCartas[0][2].toString());
                    bHabilidad.setText(dtCartas[0][3].toString());
                    bCmc.setText(Integer.toString(Integer.parseInt(dtCartas[0][4].toString())));
                    bColor.setText(dtCartas[0][5].toString());
                    bFuerza.setVisible(false);
                    bDefensa.setVisible(false);
                    separador.setVisible(false);
                    vBuscar.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "La carta indicada no se encuentra en nuestra base de datos");
                    }
                    break;
                case "Conjuro":
                    dtCartas = con.SelectCon(nombre);
                    if (dtCartas[0][0] != null){
                    bNombre.setText(dtCartas[0][0].toString());
                    bTipo.setText(dtCartas[0][1].toString());
                    bRareza.setText(dtCartas[0][2].toString());
                    bHabilidad.setText(dtCartas[0][3].toString());
                    bCmc.setText(Integer.toString(Integer.parseInt(dtCartas[0][4].toString())));
                    bColor.setText(dtCartas[0][5].toString());
                    bFuerza.setVisible(false);
                    bDefensa.setVisible(false);
                    separador.setVisible(false);
                    vBuscar.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "La carta indicada no se encuentra en nuestra base de datos");
                    }
                    break;
                case "Tierra":
                    dtCartas = con.SelectTie(nombre);
                    if (dtCartas[0][0] != null){
                    bNombre.setText(dtCartas[0][0].toString());
                    bTipo.setText(dtCartas[0][1].toString());
                    bRareza.setText(dtCartas[0][2].toString());
                    bHabilidad.setText(dtCartas[0][3].toString());
                    bFuerza.setVisible(false);
                    bDefensa.setVisible(false);
                    separador.setVisible(false);
                    bCmc.setVisible(false);
                    bColor.setVisible(false);
                    vBuscar.setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(null, "La carta indicada no se encuentra en nuestra base de datos");
                    }
                    break;
            }
        }
    }//GEN-LAST:event_bBuscarActionPerformed

    private void bAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAñadirActionPerformed
        nombre = tANombre.getText();
        habilidad = tAhabilidad.getText();
        boolean ex = false;
        if (tACmc.isEnabled()) {
            if (tACmc.getText().equalsIgnoreCase("")) {
                cmc = -1;
            } else {
                cmc = Integer.parseInt(tACmc.getText());
            }
        } else {
            cmc = 0;
        }
        dtCartas = con.Select_Cartas();
        for (int i = 0; i < dtCartas.length; i++) {
            if (nombre.equalsIgnoreCase(dtCartas[i][0].toString())) {
                ex = true;
            }
        }
        if ("".equals(nombre) || color == null || rareza == null || tipo == null || cmc == -1) {
            JOptionPane.showMessageDialog(null, "Los campos Nombre, Color, Rareza, tipo y Coste de Mana Convertido son obligatorios.");
        } else {
            if (ex == true) {
                JOptionPane.showMessageDialog(null, "No se puede añadir una carta con el mismo nombre que otra ya añadida.");
            } else {
                tAñadido.setText("Carta insertada correctamente.");
                Metodos.insertar(nombre, tipo, rareza, habilidad, cmc, color, fuerza, defensa);
                vAñadir.setVisible(true);
                this.cENombre.setModel(con.LlenarComboBox());
                this.cBNombre.setModel(con.LlenarComboBox());
            }
        }
        
    }//GEN-LAST:event_bAñadirActionPerformed

    private void bVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVisualizarActionPerformed
        //actualiza los datos de la tabla realizando una consulta a la base de datos
        String[] columNames = {"Nombre", "Tipo", "Rareza", "Habilidad"};
        dtCartas = con.Select_Cartas();
        // se colocan los datos en la tabla
        DefaultTableModel datos = new DefaultTableModel(dtCartas, columNames);
        tabla.setModel(datos);
    }//GEN-LAST:event_bVisualizarActionPerformed

    private void rAAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAAzulActionPerformed
        if (rAAzul.isSelected() == true) {
            color = "Azul";
            rABlanco.setSelected(false);
            rANegro.setSelected(false);
            rAVerde.setSelected(false);
            rARojo.setSelected(false);
            rAIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rAAzulActionPerformed

    private void rABlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rABlancoActionPerformed
        if (rABlanco.isSelected() == true) {
            color = "Blanco";
            rAAzul.setSelected(false);
            rANegro.setSelected(false);
            rAVerde.setSelected(false);
            rARojo.setSelected(false);
            rAIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rABlancoActionPerformed

    private void rANegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rANegroActionPerformed
        if (rANegro.isSelected() == true) {
            color = "Negro";
            rABlanco.setSelected(false);
            rAAzul.setSelected(false);
            rAVerde.setSelected(false);
            rARojo.setSelected(false);
            rAIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rANegroActionPerformed

    private void rAVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAVerdeActionPerformed
        if (rAVerde.isSelected() == true) {
            color = "Verde";
            rABlanco.setSelected(false);
            rAAzul.setSelected(false);
            rANegro.setSelected(false);
            rARojo.setSelected(false);
            rAIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rAVerdeActionPerformed

    private void rAIncoloroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rAIncoloroActionPerformed
        if (rAIncoloro.isSelected() == true) {
            color = "Incoloro";
            rABlanco.setSelected(false);
            rAAzul.setSelected(false);
            rANegro.setSelected(false);
            rARojo.setSelected(false);
            rAVerde.setSelected(false);
        }
    }//GEN-LAST:event_rAIncoloroActionPerformed

    private void rARojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rARojoActionPerformed
        if (rARojo.isSelected() == true) {
            color = "Rojo";
            rABlanco.setSelected(false);
            rAAzul.setSelected(false);
            rANegro.setSelected(false);
            rAIncoloro.setSelected(false);
            rAVerde.setSelected(false);
        }
    }//GEN-LAST:event_rARojoActionPerformed

    private void cAFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cAFuerzaActionPerformed
        if (cAFuerza.getSelectedIndex() == 1) {
            fuerza = -1;
        } else if (cAFuerza.getSelectedIndex() == 2) {
            fuerza = 0;
        } else if (cAFuerza.getSelectedIndex() == 3) {
            fuerza = 1;
        } else if (cAFuerza.getSelectedIndex() == 4) {
            fuerza = 2;
        } else if (cAFuerza.getSelectedIndex() == 5) {
            fuerza = 3;
        } else if (cAFuerza.getSelectedIndex() == 6) {
            fuerza = 4;
        } else if (cAFuerza.getSelectedIndex() == 7) {
            fuerza = 5;
        } else if (cAFuerza.getSelectedIndex() == 8) {
            fuerza = 6;
        } else if (cAFuerza.getSelectedIndex() == 9) {
            fuerza = 7;
        } else if (cAFuerza.getSelectedIndex() == 10) {
            fuerza = 8;
        } else if (cAFuerza.getSelectedIndex() == 11) {
            fuerza = 9;
        } else if (cAFuerza.getSelectedIndex() == 12) {
            fuerza = 10;
        } else if (cAFuerza.getSelectedIndex() == 13) {
            fuerza = 11;
        } else if (cAFuerza.getSelectedIndex() == 14) {
            fuerza = 12;
        } else if (cAFuerza.getSelectedIndex() == 15) {
            fuerza = 13;
        } else if (cAFuerza.getSelectedIndex() == 16) {
            fuerza = 14;
        } else if (cAFuerza.getSelectedIndex() == 17) {
            fuerza = 15;
        }
    }//GEN-LAST:event_cAFuerzaActionPerformed

    private void cADefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cADefensaActionPerformed
        if (cADefensa.getSelectedIndex() == 1) {
            defensa = -1;
        } else if (cADefensa.getSelectedIndex() == 2) {
            defensa = 0;
        } else if (cADefensa.getSelectedIndex() == 3) {
            defensa = 1;
        } else if (cADefensa.getSelectedIndex() == 4) {
            defensa = 2;
        } else if (cADefensa.getSelectedIndex() == 5) {
            defensa = 3;
        } else if (cADefensa.getSelectedIndex() == 6) {
            defensa = 4;
        } else if (cADefensa.getSelectedIndex() == 7) {
            defensa = 5;
        } else if (cADefensa.getSelectedIndex() == 8) {
            defensa = 6;
        } else if (cADefensa.getSelectedIndex() == 9) {
            defensa = 7;
        } else if (cADefensa.getSelectedIndex() == 10) {
            defensa = 8;
        } else if (cADefensa.getSelectedIndex() == 11) {
            defensa = 9;
        } else if (cADefensa.getSelectedIndex() == 12) {
            defensa = 10;
        } else if (cADefensa.getSelectedIndex() == 13) {
            defensa = 11;
        } else if (cADefensa.getSelectedIndex() == 14) {
            defensa = 12;
        } else if (cADefensa.getSelectedIndex() == 15) {
            defensa = 13;
        } else if (cADefensa.getSelectedIndex() == 16) {
            defensa = 14;
        } else if (cADefensa.getSelectedIndex() == 17) {
            defensa = 15;
        }
    }//GEN-LAST:event_cADefensaActionPerformed

    private void cENombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cENombreActionPerformed
        //actualiza los datos de la tabla realizando una consulta a la base de datos
        String[] columNames = {"Nombre", "Tipo", "Rareza", "Habilidad"};
        dtCartas = con.Select_Cartas();
        // se colocan los datos en la tabl
        DefaultTableModel datos = new DefaultTableModel(dtCartas, columNames);
        tabla.setModel(datos);
    }//GEN-LAST:event_cENombreActionPerformed

    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        nombre = tENombre.getText();
        habilidad = tEhabilidad.getText();
        boolean ex = false;
        if (tECmc.isEnabled()) {
            if (tECmc.getText().equalsIgnoreCase("")) {
                cmc = -1;
            } else {
                cmc = Integer.parseInt(tECmc.getText());
            }
        } else {
            cmc = 0;
        }
        nombreViejo = cENombre.getSelectedItem().toString();
        dtCartas = con.Select_Cartas();
        for (int i = 0; i < dtCartas.length; i++) {
            if (nombre.equalsIgnoreCase(dtCartas[i][0].toString())) {
                ex = true;
            }
        }
        if ("".equals(nombre) || color == null || rareza == null || tipo == null || cmc == -1) {
            JOptionPane.showMessageDialog(null, "Es necesario completar los campos Nombre, Color, Rareza, Tipo y Coste de Mana Convertido.");
        } else {
            if (ex == true && !nombre.equalsIgnoreCase(nombreViejo) ) {
                JOptionPane.showMessageDialog(null, "No esta permitido cambiar el nombre de la carta por el de otra carta ya existente.");
            } else {
                tEAñadido.setText("Carta modificada.");
                Metodos.editar(nombreViejo, nombre, tipo, rareza, habilidad, cmc, color, fuerza, defensa);
                vEditar.setVisible(true);
                this.cENombre.setModel(con.LlenarComboBox());
                this.cBNombre.setModel(con.LlenarComboBox());
            }
            
        }
    }//GEN-LAST:event_bEditarActionPerformed

    private void cERarezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cERarezaActionPerformed
        if (cERareza.getSelectedIndex() == 1) {
            rareza = "Comun";
        } else if (cERareza.getSelectedIndex() == 2) {
            rareza = "Infrecuente";
        } else if (cERareza.getSelectedIndex() == 3) {
            rareza = "Rara";
        } else if (cERareza.getSelectedIndex() == 4) {
            rareza = "Rara Mitica";
        }
    }//GEN-LAST:event_cERarezaActionPerformed

    private void cEFuerzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEFuerzaActionPerformed
        if (cEFuerza.getSelectedIndex() == 1) {
            fuerza = -1;
        } else if (cEFuerza.getSelectedIndex() == 2) {
            fuerza = 0;
        } else if (cEFuerza.getSelectedIndex() == 3) {
            fuerza = 1;
        } else if (cEFuerza.getSelectedIndex() == 4) {
            fuerza = 2;
        } else if (cEFuerza.getSelectedIndex() == 5) {
            fuerza = 3;
        } else if (cEFuerza.getSelectedIndex() == 6) {
            fuerza = 4;
        } else if (cEFuerza.getSelectedIndex() == 7) {
            fuerza = 5;
        } else if (cEFuerza.getSelectedIndex() == 8) {
            fuerza = 6;
        } else if (cEFuerza.getSelectedIndex() == 9) {
            fuerza = 7;
        } else if (cEFuerza.getSelectedIndex() == 10) {
            fuerza = 8;
        } else if (cEFuerza.getSelectedIndex() == 11) {
            fuerza = 9;
        } else if (cEFuerza.getSelectedIndex() == 12) {
            fuerza = 10;
        } else if (cEFuerza.getSelectedIndex() == 13) {
            fuerza = 11;
        } else if (cEFuerza.getSelectedIndex() == 14) {
            fuerza = 12;
        } else if (cEFuerza.getSelectedIndex() == 15) {
            fuerza = 13;
        } else if (cEFuerza.getSelectedIndex() == 16) {
            fuerza = 14;
        } else if (cEFuerza.getSelectedIndex() == 17) {
            fuerza = 15;
        }
    }//GEN-LAST:event_cEFuerzaActionPerformed

    private void cEDefensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cEDefensaActionPerformed
        if (cEDefensa.getSelectedIndex() == 1) {
            defensa = -1;
        } else if (cEDefensa.getSelectedIndex() == 2) {
            defensa = 0;
        } else if (cEDefensa.getSelectedIndex() == 3) {
            defensa = 1;
        } else if (cEDefensa.getSelectedIndex() == 4) {
            defensa = 2;
        } else if (cEDefensa.getSelectedIndex() == 5) {
            defensa = 3;
        } else if (cEDefensa.getSelectedIndex() == 6) {
            defensa = 4;
        } else if (cEDefensa.getSelectedIndex() == 7) {
            defensa = 5;
        } else if (cEDefensa.getSelectedIndex() == 8) {
            defensa = 6;
        } else if (cEDefensa.getSelectedIndex() == 9) {
            defensa = 7;
        } else if (cEDefensa.getSelectedIndex() == 10) {
            defensa = 8;
        } else if (cEDefensa.getSelectedIndex() == 11) {
            defensa = 9;
        } else if (cEDefensa.getSelectedIndex() == 12) {
            defensa = 10;
        } else if (cEDefensa.getSelectedIndex() == 13) {
            defensa = 11;
        } else if (cEDefensa.getSelectedIndex() == 14) {
            defensa = 12;
        } else if (cEDefensa.getSelectedIndex() == 15) {
            defensa = 13;
        } else if (cEDefensa.getSelectedIndex() == 16) {
            defensa = 14;
        } else if (cEDefensa.getSelectedIndex() == 17) {
            defensa = 15;
        }
    }//GEN-LAST:event_cEDefensaActionPerformed

    private void tACmcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tACmcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tACmcActionPerformed
    private void macercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_macercaActionPerformed
        vAcerca.setVisible(true);
    }//GEN-LAST:event_macercaActionPerformed
    private void mSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mSalirActionPerformed

    }//GEN-LAST:event_mSalirActionPerformed

    private void rEAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEAzulActionPerformed
        if (rEAzul.isSelected() == true) {
            color = "Azul";
            rEBlanco.setSelected(false);
            rENegro.setSelected(false);
            rEVerde.setSelected(false);
            rERojo.setSelected(false);
            rEIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rEAzulActionPerformed

    private void rEBlancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEBlancoActionPerformed
        if (rEBlanco.isSelected() == true) {
            color = "Blanco";
            rEAzul.setSelected(false);
            rENegro.setSelected(false);
            rEVerde.setSelected(false);
            rERojo.setSelected(false);
            rEIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rEBlancoActionPerformed

    private void rENegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rENegroActionPerformed
        if (rENegro.isSelected() == true) {
            color = "Negro";
            rEBlanco.setSelected(false);
            rEAzul.setSelected(false);
            rEVerde.setSelected(false);
            rERojo.setSelected(false);
            rEIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rENegroActionPerformed

    private void rERojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rERojoActionPerformed
        if (rERojo.isSelected() == true) {
            color = "Rojo";
            rEBlanco.setSelected(false);
            rEAzul.setSelected(false);
            rENegro.setSelected(false);
            rEIncoloro.setSelected(false);
            rEVerde.setSelected(false);
        }
    }//GEN-LAST:event_rERojoActionPerformed

    private void rEVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEVerdeActionPerformed
        if (rEVerde.isSelected() == true) {
            color = "Verde";
            rEBlanco.setSelected(false);
            rEAzul.setSelected(false);
            rENegro.setSelected(false);
            rERojo.setSelected(false);
            rEIncoloro.setSelected(false);
        }
    }//GEN-LAST:event_rEVerdeActionPerformed

    private void rEIncoloroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rEIncoloroActionPerformed
        if (rEIncoloro.isSelected() == true) {
            color = "Incoloro";
            rEBlanco.setSelected(false);
            rEAzul.setSelected(false);
            rENegro.setSelected(false);
            rERojo.setSelected(false);
            rEVerde.setSelected(false);
        }
    }//GEN-LAST:event_rEIncoloroActionPerformed

    private void cBNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBNombreActionPerformed
        //actualiza los datos de la tabla realizando una consulta a la base de datos
        String[] columNames = {"Nombre", "Tipo", "Rareza", "Habilidad"};
        dtCartas = con.Select_Cartas();
        // se colocan los datos en la tabl
        DefaultTableModel datos = new DefaultTableModel(dtCartas, columNames);
        tabla.setModel(datos);
    }//GEN-LAST:event_cBNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAñadir;
    private javax.swing.JButton bBuscar;
    private javax.swing.JLabel bCmc;
    private javax.swing.JLabel bColor;
    private javax.swing.JLabel bDefensa;
    private javax.swing.JButton bEditar;
    private javax.swing.JLabel bFuerza;
    private javax.swing.JTextArea bHabilidad;
    private javax.swing.JLabel bNombre;
    private javax.swing.JLabel bRareza;
    private javax.swing.JLabel bTipo;
    private javax.swing.JButton bVisualizar;
    private javax.swing.JComboBox cADefensa;
    private javax.swing.JComboBox cAFuerza;
    private javax.swing.JComboBox cARareza;
    private javax.swing.JComboBox cATipo;
    private javax.swing.JComboBox cBNombre;
    private javax.swing.JComboBox cBTipo;
    private javax.swing.JComboBox cEDefensa;
    private javax.swing.JComboBox cEFuerza;
    private javax.swing.JComboBox cENombre;
    private javax.swing.JComboBox cERareza;
    private javax.swing.JComboBox cETipo;
    private javax.swing.JLabel eACmc;
    private javax.swing.JLabel eADefensa;
    private javax.swing.JLabel eAFuerza;
    private javax.swing.JLabel eECmc;
    private javax.swing.JLabel eEDefensa;
    private javax.swing.JLabel eEFuerza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mAyuda;
    private javax.swing.JMenuItem mSalir;
    private javax.swing.JMenuItem macerca;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPanel pAñadir;
    private javax.swing.JPanel pBuscar;
    private javax.swing.JPanel pEditar;
    private javax.swing.JPanel pInicial;
    private javax.swing.JPanel pPrincipal;
    private javax.swing.JPanel pVisualizar;
    private javax.swing.JTabbedPane paneles;
    private javax.swing.JRadioButton rAAzul;
    private javax.swing.JRadioButton rABlanco;
    private javax.swing.JRadioButton rAIncoloro;
    private javax.swing.JRadioButton rANegro;
    private javax.swing.JRadioButton rARojo;
    private javax.swing.JRadioButton rAVerde;
    private javax.swing.JRadioButton rEAzul;
    private javax.swing.JRadioButton rEBlanco;
    private javax.swing.JRadioButton rEIncoloro;
    private javax.swing.JRadioButton rENegro;
    private javax.swing.JRadioButton rERojo;
    private javax.swing.JRadioButton rEVerde;
    private javax.swing.JLabel separador;
    private javax.swing.JTextField tACmc;
    private javax.swing.JTextField tANombre;
    private javax.swing.JTextArea tAhabilidad;
    private javax.swing.JLabel tAñadido;
    private javax.swing.JLabel tEAñadido;
    private javax.swing.JTextField tECmc;
    private javax.swing.JTextField tENombre;
    private javax.swing.JTextArea tEhabilidad;
    private javax.swing.JTable tabla;
    private javax.swing.JDialog vAcerca;
    private javax.swing.JDialog vAñadir;
    private javax.swing.JFrame vBuscar;
    private javax.swing.JDialog vEditar;
    // End of variables declaration//GEN-END:variables
}
